name: Test ZIP

on:
  workflow_dispatch:

jobs:
  zip-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress to zip files
        run: |
          zip airbnb-test.zip airbnb.ipynb airbnb.py airbnb_analysis.pdf

      - name: Check ZIP
        run: |
          ls -lh airbnb-test.zip
          unzip -l airbnb-test.zip
